### ISSUE TITLE
Build fails for python3.4

### ISSUE THREAD

**Issue by thliebig** [PySide/pyside2#12]
I have successfully build PySide2 on Kubuntu 15.10 (beta2) using python 2.7 and Qt5.4. Great work and nice to see PySide2 coming!

But with python 3.4 the build fails:
CMake Error at CMakeLists.txt:178 (message):
  Unsupported PYTHON_VERSION=..!

It seems that shiboken2 was found, but e.g. "$SHIBOKEN_PYTHON_VERSION_MAJOR" etc. is not set.

Any ideas?

**Comment by lockie** [comment]
Same error here, Debian Jessie, python 3.4.2.

**Comment by empyrical** [comment]
Seems as if the cmake files on Linux have trouble getting the Python versions on their own. Does it give you the same error with Python 2.7?

**Comment by thliebig** [comment]
Python 2.7 works fine. The problem is not python (I think). The variable  "$SHIBOKEN_PYTHON_VERSION_MAJOR" and so on is empty with python 3.x.

**Comment by thopiekar** [comment]
The reason is that shiboken was coded in the days where cmake had no python3 support, so they made their own implementation, which doesn't work well with the official python3 addon.
I'm not sure, but I think I made there some changes in order to get python3 packages built on Ubuntu.

**Comment by thopiekar** [comment]
Look at this line: https://github.com/PySide/shiboken2/blob/master/CMakeLists.txt#L22
So try to rebuild shiboken with `cmake USE_PYTHON3=1`.

**Comment by empyrical** [comment]
the CMake modules that come with Mac and Linux (probably windows too) have problems with finding info about the python interpreter on 3.4 and 3.5 it seems. the only reason linux users get that UNKNOWN VERSION error is because it's only on linux that the cmake scripts try to do something that use the version numbers.

The solution, I think, is to have the setup.py `-D` these variables for cmake, instead of relying completely on the cmake module finding everything

**Comment by IronManMark20** [comment]
Would it be totally evil and wrong to automatically hard-code these values from the setup.py?

**Comment by ctismer** [comment]
Not sure if I understand: does the Kubuntu build not use setup.py?
Setup.py is run by some python version, and that exactly is what shiboken2 should use.
Can you please give me exact info, so I can set up a container for testing locally?

**Comment by ctismer** [comment]
@IronManMark20 no, I think that is not wrong. Let's see what cmake does currently and why. Probably there have hacks piled up which just need a clean rewrite.

**Comment by thopiekar** [comment]
As far as I understand we always build with CMake. All Debian packages (pyside1, etc) use CMake to build.

**Comment by ctismer** [comment]
@thopiekar I will try on Debian, tomorrow and see what's going on

**Comment by ctismer** [comment]
Can somebody please try the branch `python3_unix_fix` of shiboken2 ?
I think I have removed a lot of old crap.
But now, there are build errors on Debian with Qt5.3. Maybe this is just minor.
It works on Qt5.5 with OS X.

**Comment by IronManMark20** [comment]
I'll check Windows and Ubuntu.

**Comment by lockie** [comment]
Tried on Debian Jessie (python 3.4.2, Qt 5.3.2). Still nope:

    [ 29%] Building CXX object PySide2/QtGui/CMakeFiles/QtGui.dir/PySide2/QtGui/qguiapplication_wrapper.cpp.o
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp: In function ‘void QGuiApplicationConstructor(PyObject*, PyObject*, QGuiApplicationWrapper**)’:
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:100:96: error: no matching function for call to ‘QGuiApplicationWrapper::QGuiApplicationWrapper(int&, char**&, int)’
         *cptr = new QGuiApplicationWrapper(QGuiApplicationArgCount, QGuiApplicationArgValues, 0);
                                                                                                ^
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:100:96: note: candidates are:
    In file included from /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:41:0:
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:38:5: note: QGuiApplicationWrapper::QGuiApplicationWrapper(int&, char**)
     QGuiApplicationWrapper(int & argc, char ** argv);
     ^
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:38:5: note:   candidate expects 2 arguments, 3 provided
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:35:7: note: QGuiApplicationWrapper::QGuiApplicationWrapper(const QGuiApplicationWrapper&)
     class QGuiApplicationWrapper : public QGuiApplication
       ^
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:35:7: note:   candidate expects 1 argument, 3 provided
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp: In function ‘int Sbk_QGuiApplication_Init(PyObject*, PyObject*, PyObject*)’:
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:449:80: error: no matching function for call to ‘QGuiApplicationWrapper::QGuiApplicationWrapper(int&, char*&)’
                     cptr = new (addr) ::QGuiApplicationWrapper(cppArg0, cppArg1);
                                                                                ^
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:449:80: note: candidates are:
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:113:1: note: QGuiApplicationWrapper::QGuiApplicationWrapper(int&, char**)
     QGuiApplicationWrapper::QGuiApplicationWrapper(int & argc, char ** argv) : QGuiApplication(argc, argv) {
     ^
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:113:1: note:   no known conversion for argument 2 from ‘char*’ to ‘char**’
    In file included from /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:41:0:
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:35:7: note: QGuiApplicationWrapper::QGuiApplicationWrapper(const QGuiApplicationWrapper&)
     class QGuiApplicationWrapper : public QGuiApplication
           ^
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:35:7: note:   candidate expects 1 argument, 2 provided
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:452:73: error: no matching function for call to ‘QGuiApplicationWrapper::QGuiApplicationWrapper(int&, char*&)’
                     cptr = new ::QGuiApplicationWrapper(cppArg0, cppArg1);
                                                                         ^
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:452:73: note: candidates are:
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:113:1: note: QGuiApplicationWrapper::QGuiApplicationWrapper(int&, char**)
     QGuiApplicationWrapper::QGuiApplicationWrapper(int & argc, char ** argv) : QGuiApplication(argc, argv) {
     ^
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:113:1: note:   no known conversion for argument 2 from ‘char*’ to ‘char**’
    In file included from /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:41:0:
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:35:7: note: QGuiApplicationWrapper::QGuiApplicationWrapper(const QGuiApplicationWrapper&)
     class QGuiApplicationWrapper : public QGuiApplication
           ^
    /tmp/env/pyside2-setup/pyside_build/py3.4-qt5.3.2-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:35:7: note:   candidate expects 1 argument, 2 provided

**Comment by ctismer** [comment]
@lockie but this is no longer the same error, but something with 5.3 on Python 3.4, as I already noted above. Try disabling QGuiApplication or better fixing the types in
```
pyside2-setup/sources//pyside2/PySide2/QtGui/typesystem_gui_common.xml:3255 ff
```

**Comment by IronManMark20** [comment]
So it compiles fine on Windows with Qt 5.3. Seems to be *nix specific.

**Comment by PaluMacil** [comment]
Has there been additional progress over the last 3 or so weeks? I've been meaning to try Pyside2 but am a Linux user.

**Comment by thopiekar** [comment]
There is a pull which should fix this: https://github.com/PySide/pyside2/pull/53

**Comment by thopiekar** [comment]
Since I get PySide2 built in my PPA I guess we can close this.
https://launchpad.net/~thopiekar/+archive/ubuntu/pyside-git

**Comment by thliebig** [comment]
Hi, sounds great to have a PPA. But I'm unable to install pyside2 from it:
sudo apt-get install python3-pyside2
--> _python3-pyside2 : Depends: python3-pyside2.phonon (>= 2.0.0+dev-0~201602071205~rev1847~pkg27~ubuntu15.10.1) but it is not going to be installed_
and many more like this.
Sounds like a minor problem

**Comment by thopiekar** [comment]
Ok, please open a new issue for it.
I recently made changes to it and something got broken, but I'll hopefully fix it soon.
But I'm still interested it the full log of your problem :wink:

**Comment by thliebig** [comment]
A new issue here or on launchpad?
But it seems to boil down to a missing "qtdeclarative-abi-5-4-1" package which it depends all on some levels down the chain:
_python3-pyside2 --> python3-pyside2.phonon --> libpyside-py3-2.0 --> qtdeclarative-abi-5-4-1_ (not found

**Comment by thopiekar** [comment]
Here. I don't have a bug tracker at launchpad.
Hmm, it does not make much sense. Do you have Ubuntu releases mixed up? I
even don't set these dependencies, because there are tools which browse for
the needed packages and sets them automatically.

**Comment by thliebig** [comment]
Well I use Kubuntu and I think it is the Kubuntu backport PPA that might be causing this.
_qtdeclarative-abi-5-4-1_ is just a virtual package for _libqt5qml5_, but this one is at 5.5.1 (because of the Kubuntu backports), thus this virtual-package complains... 
Anyways, my build from source worked now for the first time. Thanks!
If the PPA works for an unaltered (K)Ubuntu we may just ignore this ...

**Comment by thopiekar** [comment]
Yes, this is caused by the Kubuntu PPA. They often put an newer version of Qt into it. So my PySide builds can't install the old one.
As I moved some files between the packages there is now a problem updating them, because there are conflicts between the old and the new packages.

I'm glad to hear it works for you!
