### PR TITLE
Fix private API usage for Qt 5.6

### PR DESCRIPTION
**Pull request by empyrical**
The private APIs changed around a little bit in Qt 5.6. `currentContext()` is no longer a function and does something else, but the member `current` is the same on 5.6 and older versions.

### CODE REVIEW

**Comment by empyrical** [comment]
BTW, @ctismer: I think I remember you saying that there was something the maintainers of the Qt homebrew package did that lets PySide pick up on the module classes, that's missing from the `.dmg`s that Qt releases. What was that again?

**Comment by ctismer** [comment]
@empyrical I think that is the correct setting of Pyside include dirs. They are somehow weird in
the DMGs, but fixed by a homebrew patch. I believe we should adopt this. Without, no build works,
because Shiboken needs to find a common include folder from where it can descend to the packages.

I think that can be seen if you use `brew edit qt5`

**Comment by ctismer** [comment]
Works with Qt 5.5.1, but not with 5.4.2
Sorry, this needs version checking!

**Comment by empyrical** [comment]
Thanks for the heads-up! I'll have to give it a look in 5.3 as well. Yes, that field does also exist in 5.5 and 5.6 but i guess I didn't look too closely at 5.4's header

**Comment by ctismer** [comment]
it looks as if 5.3/5.4 had the old version, 5.4/5.5 had both, and 5.6 enforces the new version.

**Comment by empyrical** [comment]
Newest commit *should* do the trick, don't have 5.3 to test yet though.

**Comment by IronManMark20** [comment]
I am testing 5.3 atm on Windows. Will report back when done.

**Comment by IronManMark20** [comment]
Nope. :( Doesn't work.

    C:\pyside2-setup\pyside_build\py3.4-qt5.3.2-32bit-release\pyside2\libpyside\signalmanager.cpp(481) : error C3083: 'Heap': the symbol to the left of a '::' must be a type
    C:\pyside2-setup\pyside_build\py3.4-qt5.3.2-32bit-release\pyside2\libpyside\signalmanager.cpp(484) : error C3083: 'Heap': the symbol to the left of a '::' must be a type
    C:\pyside2-setup\pyside_build\py3.4-qt5.3.2-32bit-release\pyside2\libpyside\signalmanager.cpp(484) : warning C4482: nonstandard extension used: enum 'QV4::ExecutionContext::ContextType' used in qualified name
    C:\pyside2-setup\pyside_build\py3.4-qt5.3.2-32bit-release\pyside2\libpyside\signalmanager.cpp(485) : error C3083: 'Heap': the symbol to the left of a '::' must be a type
    C:\pyside2-setup\pyside_build\py3.4-qt5.3.2-32bit-release\pyside2\libpyside\signalmanager.cpp(485) : warning C4482: nonstandard extension used: enum 'QV4::ExecutionContext::ContextType' used in qualified name
    C:\pyside2-setup\pyside_build\py3.4-qt5.3.2-32bit-release\pyside2\libpyside\signalmanager.cpp(495) : error C2039: 'throwSyntaxError' : is not a member of 'QV4::ExecutionEngine'
            C:\Qt\Qt5.3.2\5.3\msvc2010_opengl\include\QtQml\5.3.2\QtQml\private/qv4engine_p.h(127) : see declaration of 'QV4::ExecutionEngine'
    C:\pyside2-setup\pyside_build\py3.4-qt5.3.2-32bit-release\pyside2\libpyside\signalmanager.cpp(497) : error C2039: 'throwTypeError' : is not a member of 'QV4::ExecutionEngine'
            C:\Qt\Qt5.3.2\5.3\msvc2010_opengl\include\QtQml\5.3.2\QtQml\private/qv4engine_p.h(127) : see declaration of 'QV4::ExecutionEngine'
    C:\pyside2-setup\pyside_build\py3.4-qt5.3.2-32bit-release\pyside2\libpyside\signalmanager.cpp(499) : error C2039: 'throwError' : is not a member of 'QV4::ExecutionEngine'
            C:\Qt\Qt5.3.2\5.3\msvc2010_opengl\include\QtQml\5.3.2\QtQml\private/qv4engine_p.h(127) : see declaration of 'QV4::ExecutionEngine'
    NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~4.0\VC\bin\cl.exe' : return code '0x2'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\nmake.exe"' : return code '0x2'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\nmake.exe"' : return code '0x2'
    Stop.
    error: Error compiling pyside2 

Python 3.4 MSVC 2010 Qt 5.3.2

**Comment by empyrical** [comment]
Wow, there's some pretty serious churn happening in the V4 APIs! Will have to finish getting 5.3 set up on my system to figure this out

**Comment by empyrical** [comment]
Hmm, I think it might be appropriate to yank this error handling code out for now, and come back to it with the  implementation of #50 as the QMLV4Function overload would be the "proper" way to do it. Thoughts, @ctismer?

**Comment by ctismer** [comment]
I'm at least happy with this, because 5.4 was the version that I began with, and so far it is OK.
